### ISSUE TITLE
(not an issue im just stupid) how exactly do u use this

### ISSUE THREAD

**Issue by Cheekpost** [CustomPayload/Skyblock-Rat#1]

**Comment by KTibow** [comment]
...

**Comment by Napoleon-x** [comment]
> _No description provided._

You are not very smart, are you?

**Comment by CustomPayload** [comment]
This is not an issue of the logger, its a skill issue :trollface:

**Comment by KTibow** [comment]
wait do they seriously have :trollface: in github now
LMAO
