### ISSUE TITLE
Saddening

### ISSUE THREAD

**Issue by 84** [CustomPayload/Skyblock-Rat#11]
Delete this repository. One of the worst projects I have ever seen. The fact you would actually put a watermark in this like anyone would want to copy this shit is absolutely embarrassing.

**Comment by CustomPayload** [comment]
A TON of people have used this, you are just mad L

**Comment by CustomPayload** [comment]
Would you look at those forks and all of those stars + the many people that message me daily about it

**Comment by 84** [comment]
None of these forks contribute anything and are therefore worthless. "All of those stars" not sure why you are flexing 14 stars. None of this changes how dogshit your "code" is which is most definitely pasted from multiple other "RATs" (this is not a rat).

**Comment by CustomPayload** [comment]
many people leech so not that people star it lol. + im trying to improve the code lol. still makes it a very good java rat and a lot of people DO use it.

**Comment by 84** [comment]
This is not a java RAT.

**Comment by CustomPayload** [comment]
Most people call it a rat so thats why i put RAT/Logger, most of the times i say rat when i mean logger
