### ISSUE TITLE
what the fuck is this shit malware lmao

### ISSUE THREAD

**Issue by Vendicated** [CustomPayload/Skyblock-Rat#13]
This is literally the skiddiest malware I have ever seen not only did you choose the worst language to do this in cause you can literally decompile it to nearly source form but you also suck at Java and dont realise that splitting the webhook into multiple strings is useless cause the compiler just turns it into one string anyway. Seriously reconsider your life choices lmao this is just sad man

**Comment by Vendicated** [comment]
Just realised its not even you whos distributing it on discord lmao that just makes it even sadder some random 16yo is distributing this shit

**Comment by CustomPayload** [comment]
i hope you realise how retarded you look in this "issue" when its really your issue. if you clearly use your fucking eyes you would be able to see the name as Skyblock-Rat. a HYPIXEL SKYBLOCK rat. and what is that gamemode played in? Java! EXXXXXACTLY. What did you want me to write a fucking java application in python or something are you braindead. Also would you think i would post an OBFUSCATED source on an OPEN SOURCE website? exactly dumbass, i wouldnt. + the multiple strings are for deobfuscators.

**Comment by Vendicated** [comment]
> the multiple strings are for deobfuscators

yeah but the compiler just merges them lmao do you not know how compilers work :trollface:

**Comment by CustomPayload** [comment]
It was for retarded deobfuscators.+ I do know how compilers work
