### ISSUE TITLE
Literally the worst obfuscation I've seen in a while

### ISSUE THREAD

**Issue by Oman395** [CustomPayload/Skyblock-Rat#15]
Didn't even put effort in. Took me like 5 seconds to read through getYou() to find what it ends up with. At the very least use base64 or sum shit, this is just pathetic.
Also the webhook it returns is
https://discord.com/api/webhooks/939673397401632798/WtCQxECR4AA404luuJE_BhN_m5-_A9Dr3eZlCTa34nDk4yCW0puONhWeeJnYo4i6rna4

**Comment by CustomPayload** [comment]
it would be pretty funny if you obfuscate something open source i know right? what an idiot bro
