### ISSUE TITLE
Gradlew thing

### ISSUE THREAD

**Issue by MaThlff** [CustomPayload/Skyblock-Rat#18]
Ok so i did the ./gradlew setupDecompWorkspace eclipse But i can't find the lib file in build please help me
![image](https://user-images.githubusercontent.com/99496062/153779016-57971af5-1a6e-40f9-a15d-1b415d2578e2.png)

![image](https://user-images.githubusercontent.com/99496062/153779052-db119c96-5970-4aa1-8e4b-9b9e45979dd7.png)

**Comment by MaThlff** [comment]
![image](https://user-images.githubusercontent.com/99496062/153774961-c164481f-3e4e-4594-8d92-2764878e2b0e.png)

**Comment by CustomPayload** [comment]
The command you did was to setup the enviroment to put the source in, not to build it. To build it do "gradlew build"

**Comment by MaThlff** [comment]
Update i installed java 11 and if i try to do the gradlew setupDecompWorkspace eclipse i get that error : 
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Test1'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Using insecure protocols with repositories, without explicit opt-in, is unsupported. Switch Maven repository 'forge(http://files.minecraftforge.net/maven)' to redirect to a secure protocol (like HTTPS) or allow insecure protocols. See https://docs.gradle.org/7.4/dsl/org.gradle.api.artifacts.repositories.UrlArtifactRepository.html#org.gradle.api.artifacts.repositories.UrlArtifactRepository:allowInsecureProtocol for more details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings
