### ISSUE TITLE
How do I compile this into a .jar?

### ISSUE THREAD

**Issue by GigaAlex9** [CustomPayload/Skyblock-Rat#8]

**Comment by GigaAlex9** [comment]
Setup

Download the Forge 1.8.9 MDK at the forge website, extract it to a folder, open command prompt and type gradlew setupDecompWorkspace eclipse after you did that you can open eclipse at the location in the folder eclipse. Change webhook
You might also wanna change the MODID, VERSION and the mcmod.info file Dont change the CustomPayload made this or the CustomPayloadOnTop
Compiling

Open the command prompt to the location of your mdk and type gradlew build and it will build for you. You will find the compiled jar file in build/libs/modid-1.0.jar You can also rename the file.

**Comment by GigaAlex9** [comment]
When trying to compile it's stuck at this decompilemc at 56%

**Comment by CustomPayload** [comment]
Stop spamming issues, this is NOT a rat issue
